######## ember-osf settings ########
local:
    CLIENT_ID: 34b018930e2d40bfa131154cbdb38ace
    PERSONAL_ACCESS_TOKEN: null
    OAUTH_SCOPES: osf.full_read osf.full_write
    REDIRECT_URI: http://localhost:4200/login/
# stage:
#    CLIENT_ID: null
#    PERSONAL_ACCESS_TOKEN: null
#    OAUTH_SCOPES: osf.full_read osf.full_write
#    REDIRECT_URI: http://localhost:4200/login/

# stage2:
#    CLIENT_ID: null
#    PERSONAL_ACCESS_TOKEN: null
#    OAUTH_SCOPES: osf.full_read osf.full_write
#    REDIRECT_URI: http://localhost:4200/login/

#test:
#    CLIENT_ID: null
#    PERSONAL_ACCESS_TOKEN: null
#    OAUTH_SCOPES: osf.full_read osf.full_write
#    REDIRECT_URI: http://localhost:4200/login/
########## end ember-osf ##########
