####### ember-osf settings ########
local:
  CLIENT_ID: TvVtdSA02JM0TrDR4YR4jDEJ1BTTvW2RiR7pA1ZT
  PERSONAL_ACCESS_TOKEN: JPuL17RoYVdeGeoZfZtGc9MPFDlXu3dYEUrnVrXU2F7PRaUFDLruj4KXm7vfEzZwN5SWPi
  OAUTH_SCOPES: osf.full_read osf.full_write

stage:
   CLIENT_ID: 8bce2d2ed769427dbfbf3d3ca29f78b6
   PERSONAL_ACCESS_TOKEN: null
   OAUTH_SCOPES: osf.full_read osf.full_write

# stage2:
#   CLIENT_ID: null
#   PERSONAL_ACCESS_TOKEN: null
#   OAUTH_SCOPES: osf.full_read osf.full_write

# test:
#   CLIENT_ID: null
#   PERSONAL_ACCESS_TOKEN: null
#   OAUTH_SCOPES: osf.full_read osf.full_write
######### end ember-osf ##########
